### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/code-journal#9]
## 💰 Motivation

Improve and optimize code.

## 📐 Plan

Refactor to ES6 where applicable

## ✅ Task List

- [x] Change all JavaScript variables to const or let, and ensure names are intuitive 
- [x] Add favicon to index.html
- [x] Add cursor:pointer to navbar
- [x] Change all functions to use ES6 arrow functions
